[production]
environment = "production"
gunicorn = true
host = "10.148.0.10" #internal ip
flask_config = { port = 5000, debug = false }

[development]
environment = "development"
# if you are running without gunicorn locally, make this false
gunicorn = false
host = "192.168.1.103" #internal ip
debug = true
flask_config = { port = 5000, debug = true }
